# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('time_slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subject.Subject')),
                ('time_slot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot1', to='time_slot.Time_Slot')),
                ('time_slot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot2', to='time_slot.Time_Slot')),
            ],
        ),
    ]
