# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190617_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='time_slot1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time_slot2',
        ),
    ]
