# Generated by Django 2.2.2 on 2019-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exercise',
        ),
    ]
