# Generated by Django 2.2.2 on 2019-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_file_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_snippet',
            field=models.BooleanField(default=False),
        ),
    ]
