# Generated by Django 2.2.2 on 2019-08-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='file',
        ),
    ]
