# Generated by Django 2.2.2 on 2019-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_exercise_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exam',
        ),
    ]
