# Generated by Django 2.2.2 on 2019-08-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_exercise'),
        ('exercise', '0003_remove_exercise_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam'),
        ),
    ]
