# Generated by Django 2.2.2 on 2019-08-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='exam.Exam'),
        ),
    ]
