# Generated by Django 2.2.2 on 2019-06-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_building', models.CharField(max_length=255, unique=True)),
                ('file_obj', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
        migrations.CreateModel(
            name='TimeSlotLabMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Lab')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Time_Slot')),
            ],
            options={
                'db_table': 'timeslot_lab_memberships',
            },
        ),
        migrations.AddField(
            model_name='time_slot',
            name='labs',
            field=models.ManyToManyField(through='lab.TimeSlotLabMembership', to='lab.Lab'),
        ),
        migrations.CreateModel(
            name='LabIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_ips', to='lab.Lab')),
            ],
            options={
                'db_table': 'lab_ips',
                'ordering': ['-date_created'],
            },
        ),
    ]
