# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_admin',
            field=models.ForeignKey(default='301a0d85-b4cf-4eb8-ba01-8b60d64aff72', on_delete=django.db.models.deletion.CASCADE, related_name='lab', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labip',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='std_lab_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labip',
            name='student1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='std1_lab_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labip',
            name='student2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='std2_lab_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='labip',
            unique_together=set([('lab', 'ip')]),
        ),
    ]
