# Generated by Django 2.2.2 on 2019-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20190630_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
