# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20190604_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labip',
            name='student',
        ),
    ]
