# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0002_labip'),
    ]

    operations = [
        migrations.AddField(
            model_name='labip',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_ip', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='labip',
            unique_together=set([('student', 'lab', 'ip')]),
        ),
    ]
