# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190617_1411'),
        ('lab', '0003_remove_labip_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab', to='exam.Exam'),
        ),
    ]
