# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20190520_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labip',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_ip', to=settings.AUTH_USER_MODEL),
        ),
    ]
