# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20190520_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
