# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20190617_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to=settings.AUTH_USER_MODEL),
        ),
    ]
