# Generated by Django 2.2.1 on 2019-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20190619_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('labs', models.ManyToManyField(to='lab.Lab')),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
    ]
