# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20190620_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='labs',
            field=models.ManyToManyField(blank=True, null=True, related_name='time_slots', to='lab.Lab'),
        ),
    ]
