# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190624_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotLabMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Lab')),
            ],
            options={
                'db_table': 'timeslot_lab_memberships',
            },
        ),
        migrations.RemoveField(
            model_name='time_slot',
            name='labs',

        ),
        migrations.AddField(
            model_name='timeslotlabmembership',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Time_Slot'),
        ),
    ]
