# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20190624_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slot',
            name='labs',
            field=models.ManyToManyField(through='lab.TimeSlotLabMembership', to='lab.Lab'),
        ),
    ]
