# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_time_slot_labs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labip',
            name='student1',
        ),
        migrations.RemoveField(
            model_name='labip',
            name='student2',
        ),
    ]
