# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeslot',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
