# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exam_user'),
        ('user', '0002_user_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='exam.Exam'),
        ),
    ]
