# Generated by Django 2.2.2 on 2019-09-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190630_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='lab.LabIp'),
        ),
    ]
