# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190520_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'labadmin'), (4, 'admin')], default=1),
        ),
    ]
